spring.application.name=mundane-map-vaadin-viewer
vaadin.launch-browser=false
vaadin.react.enable=false
vaadin.pnpm.enable=false
vaadin.devmode.usageStatistics.enabled=false
server.address=127.0.0.1
spring.servlet.multipart.max-file-size=16MB
spring.servlet.multipart.max-request-size=33MB
spring.servlet.multipart.file-size-threshold=0
