package io.github.mundanej.map.buildlogic;

import java.io.IOException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import javax.inject.Inject;
import javax.xml.XMLConstants;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import org.gradle.api.DefaultTask;
import org.gradle.api.GradleException;
import org.gradle.api.file.ConfigurableFileCollection;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.provider.MapProperty;
import org.gradle.api.provider.SetProperty;
import org.gradle.api.tasks.CacheableTask;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.InputFile;
import org.gradle.api.tasks.InputFiles;
import org.gradle.api.tasks.Internal;
import org.gradle.api.tasks.OutputFile;
import org.gradle.api.tasks.PathSensitive;
import org.gradle.api.tasks.PathSensitivity;
import org.gradle.api.tasks.TaskAction;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.jacoco.core.analysis.Analyzer;
import org.jacoco.core.analysis.CoverageBuilder;
import org.jacoco.core.analysis.IClassCoverage;
import org.jacoco.core.analysis.ISourceFileCoverage;
import org.jacoco.core.data.ExecutionDataStore;
import org.xml.sax.SAXException;

/** Inventories physical production sources and enforces JaCoCo coverage per source file. */
@CacheableTask
public abstract class VerifySourceFileCoverage extends DefaultTask {
    /** Creates a task instance whose properties Gradle configures before execution. */
    @Inject
    public VerifySourceFileCoverage() {}

    /**
     * Provides the project directory used to render stable project-relative paths.
     *
     * @return project directory
     */
    @Internal
    public abstract DirectoryProperty getProjectDirectory();

    /**
     * Provides the hand-authored production source directories.
     *
     * @return production source directories
     */
    @InputFiles
    @PathSensitive(PathSensitivity.RELATIVE)
    public abstract ConfigurableFileCollection getSourceDirectories();

    /**
     * Provides independently inventoried production class directories.
     *
     * @return compiled production class directories
     */
    @InputFiles
    @PathSensitive(PathSensitivity.RELATIVE)
    public abstract ConfigurableFileCollection getCompiledClassDirectories();

    /**
     * Provides generated-source roots beneath the project build directory.
     *
     * @return generated-source roots
     */
    @InputFiles
    @PathSensitive(PathSensitivity.RELATIVE)
    public abstract ConfigurableFileCollection getGeneratedSourceDirectories();

    /**
     * Provides the JaCoCo XML report containing class-to-source mappings and counters.
     *
     * @return JaCoCo XML report
     */
    @InputFile
    @PathSensitive(PathSensitivity.RELATIVE)
    public abstract RegularFileProperty getXmlReport();

    /**
     * Provides the exact source keys generated by a verified build step and omitted from the
     * hand-authored inventory.
     *
     * @return exact generated source keys
     */
    @Input
    public abstract SetProperty<String> getGeneratedSourceKeys();

    /**
     * Provides exact JaCoCo-source-key to physical-source-key mappings for generated compilers.
     *
     * @return exact source aliases
     */
    @Input
    public abstract MapProperty<String, String> getSourceAliases();

    /**
     * Provides the required source-file instruction covered ratio.
     *
     * @return required covered ratio
     */
    @Input
    public abstract Property<BigDecimal> getMinimum();

    /**
     * Provides the stable Gradle project identity used in diagnostics.
     *
     * @return Gradle project identity
     */
    @Input
    public abstract Property<String> getProjectIdentity();

    /**
     * Provides the deterministic machine-readable CSV report.
     *
     * @return CSV report
     */
    @OutputFile
    public abstract RegularFileProperty getCsvReport();

    /**
     * Provides the deterministic coding-agent-readable Markdown report.
     *
     * @return Markdown report
     */
    @OutputFile
    public abstract RegularFileProperty getMarkdownReport();

    /** Writes both reports and fails after listing every source below the configured minimum. */
    @TaskAction
    void verify() throws IOException, ParserConfigurationException, SAXException {
        execute(
                getProjectDirectory().get().getAsFile().toPath(),
                getSourceDirectories().getFiles().stream().map(java.io.File::toPath).toList(),
                getCompiledClassDirectories().getFiles().stream()
                        .map(java.io.File::toPath)
                        .toList(),
                getGeneratedSourceDirectories().getFiles().stream()
                        .map(java.io.File::toPath)
                        .toList(),
                getXmlReport().get().getAsFile().toPath(),
                getGeneratedSourceKeys().get(),
                getSourceAliases().get(),
                getMinimum().get(),
                getProjectIdentity().get(),
                getCsvReport().get().getAsFile().toPath(),
                getMarkdownReport().get().getAsFile().toPath());
    }

    /**
     * Runs the standalone verifier for build logic, whose classes are not available while its own
     * build script is being configured.
     *
     * @param arguments project directory, XML report, minimum, identity, CSV report, Markdown
     *     report, generated-source count and keys, alias count and key/value pairs,
     *     generated-root count and roots, compiled-class-directory count and directories, followed
     *     by source directories
     * @throws IllegalArgumentException when the argument structure is incomplete
     * @throws Exception when arguments, reports, or coverage policy are invalid
     */
    public static void main(String[] arguments) throws Exception {
        if (arguments.length < 8) {
            throw new IllegalArgumentException("Expected at least eight coverage arguments");
        }
        int generatedCount = Integer.parseInt(arguments[6]);
        int aliasCountIndex = 7 + generatedCount;
        int aliasCount = Integer.parseInt(arguments[aliasCountIndex]);
        int firstSource = aliasCountIndex + 1 + aliasCount * 2;
        if (arguments.length <= firstSource) {
            throw new IllegalArgumentException("Expected at least one production source directory");
        }
        Set<String> generated = new TreeSet<>();
        for (int index = 7; index < firstSource; index++) {
            if (index == aliasCountIndex) {
                break;
            }
            generated.add(arguments[index]);
        }
        Map<String, String> aliases = new TreeMap<>();
        for (int index = aliasCountIndex + 1; index < firstSource; index += 2) {
            aliases.put(arguments[index], arguments[index + 1]);
        }
        int generatedRootCountIndex = firstSource;
        int generatedRootCount = Integer.parseInt(arguments[generatedRootCountIndex]);
        int firstClassCount = generatedRootCountIndex + 1 + generatedRootCount;
        int classDirectoryCount = Integer.parseInt(arguments[firstClassCount]);
        int firstSourceDirectory = firstClassCount + 1 + classDirectoryCount;
        if (arguments.length <= firstSourceDirectory) {
            throw new IllegalArgumentException("Expected at least one production source directory");
        }
        List<Path> generatedRoots = new ArrayList<>();
        for (int index = generatedRootCountIndex + 1; index < firstClassCount; index++) {
            generatedRoots.add(Path.of(arguments[index]));
        }
        List<Path> classDirectories = new ArrayList<>();
        for (int index = firstClassCount + 1; index < firstSourceDirectory; index++) {
            classDirectories.add(Path.of(arguments[index]));
        }
        List<Path> sources = new ArrayList<>();
        for (int index = firstSourceDirectory; index < arguments.length; index++) {
            sources.add(Path.of(arguments[index]));
        }
        execute(
                Path.of(arguments[0]),
                sources,
                classDirectories,
                generatedRoots,
                Path.of(arguments[1]),
                generated,
                aliases,
                new BigDecimal(arguments[2]),
                arguments[3],
                Path.of(arguments[4]),
                Path.of(arguments[5]));
    }

    private static void execute(
            Path configuredProjectDirectory,
            Iterable<Path> sourceDirectories,
            Iterable<Path> compiledClassDirectories,
            Iterable<Path> generatedSourceDirectories,
            Path xmlReport,
            Set<String> configuredGenerated,
            Map<String, String> aliases,
            BigDecimal minimum,
            String projectIdentity,
            Path csvReport,
            Path markdownReport)
            throws IOException, ParserConfigurationException, SAXException {
        Path projectDirectory = configuredProjectDirectory.normalize();
        Map<String, SourceInventory> inventory = inventory(projectDirectory, sourceDirectories);
        CoverageDocument structure = analyzeClasses(compiledClassDirectories);
        validateAliases(inventory, structure, aliases);
        structure = applyAliases(structure, aliases);
        CoverageDocument coverage = applyAliases(parseCoverage(xmlReport), aliases);
        Set<String> generated = new TreeSet<>(configuredGenerated);
        validateGenerated(
                projectDirectory,
                inventory,
                structure,
                generated,
                generatedSourceDirectories,
                projectIdentity);
        generated.forEach(inventory::remove);

        Set<String> unknownCoverage = new TreeSet<>(coverage.sources().keySet());
        unknownCoverage.removeAll(inventory.keySet());
        unknownCoverage.removeAll(generated);
        if (!unknownCoverage.isEmpty()) {
            throw new GradleException(
                    "JaCoCo coverage references sources outside the authoritative inventory for "
                            + projectIdentity
                            + ": "
                            + unknownCoverage);
        }
        Set<String> unknownClasses = new TreeSet<>(structure.sources().keySet());
        unknownClasses.removeAll(inventory.keySet());
        unknownClasses.removeAll(generated);
        if (!unknownClasses.isEmpty()) {
            throw new GradleException(
                    "Compiled classes reference sources outside the authoritative inventory for "
                            + projectIdentity
                            + ": "
                            + unknownClasses);
        }
        Set<String> absentGenerated = new TreeSet<>(generated);
        absentGenerated.removeAll(structure.sources().keySet());
        if (!absentGenerated.isEmpty()) {
            throw new GradleException(
                    "Configured generated JaCoCo sources were not present for "
                            + projectIdentity
                            + ": "
                            + absentGenerated);
        }

        List<CoverageRow> rows = new ArrayList<>();
        for (var entry : inventory.entrySet()) {
            SourceCoverage counters = coverage.sources().get(entry.getKey());
            SourceCoverage compiled = structure.sources().get(entry.getKey());
            List<String> classes =
                    structure.classes().getOrDefault(entry.getKey(), List.of());
            if (compiled == null || compiled.total() == 0) {
                rows.add(
                        new CoverageRow(
                                entry.getValue().relativePath(),
                                classes,
                                0,
                                0,
                                null,
                                "NO_INSTRUCTIONS"));
            } else if (counters == null) {
                rows.add(
                        new CoverageRow(
                                entry.getValue().relativePath(),
                                classes,
                                compiled.total(),
                                0,
                                null,
                                "MISSING_COVERAGE"));
            } else {
                BigDecimal ratio = ratio(counters.covered(), counters.total());
                rows.add(
                        new CoverageRow(
                                entry.getValue().relativePath(),
                                classes,
                                counters.missed(),
                                counters.covered(),
                                ratio,
                                ratio.compareTo(minimum) >= 0
                                        ? "PASS"
                                        : "VIOLATION"));
            }
        }
        rows.sort(Comparator.comparing(CoverageRow::path));
        writeCsv(rows, csvReport);
        writeMarkdown(rows, markdownReport);

        List<String> violations =
                rows.stream()
                        .filter(
                                row ->
                                        row.status().equals("VIOLATION")
                                                || row.status().equals("MISSING_COVERAGE"))
                        .map(
                                row ->
                                        row.path()
                                                + " INSTRUCTION/COVEREDRATIO actual="
                                                + (row.ratio() == null
                                                        ? "missing"
                                                        : format(row.ratio()))
                                                + " required="
                                                + format(minimum))
                        .toList();
        if (!violations.isEmpty()) {
            throw new GradleException(
                    "Per-source coverage violations for "
                            + projectIdentity
                            + ":\n"
                            + String.join("\n", violations));
        }
    }

    private static CoverageDocument applyAliases(
            CoverageDocument coverage, Map<String, String> aliases) {
        Set<String> absentAliases = new TreeSet<>(aliases.keySet());
        absentAliases.removeAll(coverage.sources().keySet());
        if (!absentAliases.isEmpty()) {
            throw new GradleException(
                    "Configured JaCoCo source aliases were not present: " + absentAliases);
        }
        Map<String, SourceCoverage> sources = new TreeMap<>();
        coverage.sources().forEach(
                (key, value) ->
                        sources.merge(
                                aliases.getOrDefault(key, key),
                                value,
                                (first, second) ->
                                        new SourceCoverage(
                                                first.missed() + second.missed(),
                                                first.covered() + second.covered())));
        Map<String, Set<String>> classSets = new TreeMap<>();
        coverage.classes().forEach(
                (key, value) ->
                        classSets
                                .computeIfAbsent(
                                        aliases.getOrDefault(key, key),
                                        ignored -> new TreeSet<>())
                                .addAll(value));
        Map<String, List<String>> classes = new TreeMap<>();
        classSets.forEach((key, value) -> classes.put(key, List.copyOf(value)));
        return new CoverageDocument(Map.copyOf(sources), Map.copyOf(classes));
    }

    private static void validateAliases(
            Map<String, SourceInventory> inventory,
            CoverageDocument structure,
            Map<String, String> aliases) {
        Set<String> inventoryAliases = new TreeSet<>(aliases.keySet());
        inventoryAliases.retainAll(inventory.keySet());
        if (!inventoryAliases.isEmpty()) {
            throw new GradleException(
                    "JaCoCo source aliases must be compiler artifacts, not physical inventory"
                            + " sources: "
                            + inventoryAliases);
        }
        Set<String> absentTargets = new TreeSet<>(aliases.values());
        absentTargets.removeAll(inventory.keySet());
        if (!absentTargets.isEmpty()) {
            throw new GradleException(
                    "JaCoCo source alias targets were not physical inventory sources: "
                            + absentTargets);
        }
        Set<String> absentArtifacts = new TreeSet<>(aliases.keySet());
        absentArtifacts.removeAll(structure.sources().keySet());
        if (!absentArtifacts.isEmpty()) {
            throw new GradleException(
                    "JaCoCo source aliases were not compiled artifacts: " + absentArtifacts);
        }
    }

    private static void validateGenerated(
            Path projectDirectory,
            Map<String, SourceInventory> inventory,
            CoverageDocument structure,
            Set<String> generated,
            Iterable<Path> configuredRoots,
            String projectIdentity) {
        Path buildDirectory = projectDirectory.resolve("build").normalize();
        List<Path> roots = new ArrayList<>();
        for (Path configuredRoot : configuredRoots) {
            Path root = configuredRoot.normalize();
            if (!root.startsWith(buildDirectory)) {
                throw new GradleException(
                        "Generated-source root must be beneath "
                                + slash(buildDirectory)
                                + ": "
                                + slash(root));
            }
            roots.add(root);
        }
        Set<String> invalid = new TreeSet<>();
        for (String key : generated) {
            SourceInventory source = inventory.get(key);
            boolean physicalInventoryGenerated =
                    source != null
                            && roots.stream()
                                    .anyMatch(root -> source.physicalPath().startsWith(root));
            boolean generatedArtifact =
                    source == null
                            && roots.stream()
                                    .map(root -> root.resolve(key).normalize())
                                    .anyMatch(
                                            candidate ->
                                                    roots.stream()
                                                                    .anyMatch(
                                                                            root ->
                                                                                    candidate
                                                                                            .startsWith(
                                                                                                    root))
                                                            && Files.isRegularFile(candidate));
            if ((!physicalInventoryGenerated && !generatedArtifact)
                    || !structure.sources().containsKey(key)) {
                invalid.add(key);
            }
        }
        if (!invalid.isEmpty()) {
            throw new GradleException(
                    "Configured generated sources lacked exact build-output provenance for "
                            + projectIdentity
                            + ": "
                            + invalid);
        }
    }

    private static Map<String, SourceInventory> inventory(
            Path projectDirectory, Iterable<Path> sourceDirectories) throws IOException {
        Map<String, SourceInventory> sources = new TreeMap<>();
        for (Path directory : sourceDirectories) {
            Path root = directory.normalize();
            if (!Files.isDirectory(root)) {
                continue;
            }
            try (var paths = Files.walk(root)) {
                for (Path source :
                        paths.filter(Files::isRegularFile)
                                .filter(VerifySourceFileCoverage::isProductionSource)
                                .sorted()
                                .toList()) {
                    String key = slash(root.relativize(source));
                    String relative = slash(projectDirectory.relativize(source));
                    SourceInventory previous =
                            sources.putIfAbsent(
                                    key,
                                    new SourceInventory(
                                            relative, source.toAbsolutePath().normalize()));
                    if (previous != null) {
                        throw new GradleException(
                                "Duplicate production source key "
                                        + key
                                        + ": "
                                        + previous.relativePath()
                                        + " and "
                                        + relative);
                    }
                }
            }
        }
        return sources;
    }

    private static CoverageDocument analyzeClasses(Iterable<Path> classDirectories)
            throws IOException {
        CoverageBuilder coverage = new CoverageBuilder();
        Analyzer analyzer = new Analyzer(new ExecutionDataStore(), coverage);
        for (Path directory : classDirectories) {
            if (Files.isDirectory(directory)) {
                analyzer.analyzeAll(directory.toFile());
            }
        }
        Map<String, SourceCoverage> sources = new TreeMap<>();
        for (ISourceFileCoverage source : coverage.getSourceFiles()) {
            String key = sourceKey(source.getPackageName(), source.getName());
            sources.put(
                    key,
                    new SourceCoverage(
                            source.getInstructionCounter().getTotalCount(), 0));
        }
        Map<String, Set<String>> classSets = new TreeMap<>();
        for (IClassCoverage type : coverage.getClasses()) {
            String sourceName = type.getSourceFileName();
            if (sourceName != null && !sourceName.isBlank()) {
                String key = sourceKey(type.getPackageName(), sourceName);
                classSets
                        .computeIfAbsent(key, ignored -> new TreeSet<>())
                        .add(type.getName().replace('/', '.'));
            }
        }
        Map<String, List<String>> classes = new TreeMap<>();
        classSets.forEach((key, value) -> classes.put(key, List.copyOf(value)));
        return new CoverageDocument(Map.copyOf(sources), Map.copyOf(classes));
    }

    private static CoverageDocument parseCoverage(Path xmlReport)
            throws IOException, ParserConfigurationException, SAXException {
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        factory.setFeature("http://xml.org/sax/features/external-general-entities", false);
        factory.setFeature("http://xml.org/sax/features/external-parameter-entities", false);
        factory.setFeature(
                "http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
        factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, "");
        factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_SCHEMA, "");
        Element report =
                factory.newDocumentBuilder()
                        .parse(xmlReport.toFile())
                        .getDocumentElement();
        Map<String, SourceCoverage> sources = new HashMap<>();
        Map<String, Set<String>> classes = new HashMap<>();
        for (Element packageElement : children(report, "package")) {
            String packageName = packageElement.getAttribute("name");
            for (Element classElement : children(packageElement, "class")) {
                String sourceName = classElement.getAttribute("sourcefilename");
                if (!sourceName.isBlank()) {
                    String key = sourceKey(packageName, sourceName);
                    classes.computeIfAbsent(key, ignored -> new TreeSet<>())
                            .add(classElement.getAttribute("name").replace('/', '.'));
                }
            }
            for (Element sourceElement : children(packageElement, "sourcefile")) {
                String key = sourceKey(packageName, sourceElement.getAttribute("name"));
                Element instruction =
                        children(sourceElement, "counter").stream()
                                .filter(
                                        counter ->
                                                counter.getAttribute("type").equals("INSTRUCTION"))
                                .findFirst()
                                .orElse(null);
                if (instruction != null) {
                    sources.put(
                            key,
                            new SourceCoverage(
                                    Integer.parseInt(instruction.getAttribute("missed")),
                                    Integer.parseInt(instruction.getAttribute("covered"))));
                }
            }
        }
        Map<String, List<String>> sortedClasses = new TreeMap<>();
        classes.forEach((key, value) -> sortedClasses.put(key, List.copyOf(value)));
        return new CoverageDocument(Map.copyOf(sources), Map.copyOf(sortedClasses));
    }

    private static void writeCsv(List<CoverageRow> rows, Path csvReport) throws IOException {
        StringBuilder csv =
                new StringBuilder("source,classes,missed,covered,ratio,status\n");
        for (CoverageRow row : rows) {
            csv.append(quote(row.path()))
                    .append(',')
                    .append(quote(String.join(";", row.classes())))
                    .append(',')
                    .append(row.missed())
                    .append(',')
                    .append(row.covered())
                    .append(',')
                    .append(row.ratio() == null ? "" : format(row.ratio()))
                    .append(',')
                    .append(row.status())
                    .append('\n');
        }
        write(csvReport, csv.toString());
    }

    private static void writeMarkdown(List<CoverageRow> rows, Path markdownReport)
            throws IOException {
        StringBuilder markdown =
                new StringBuilder(
                        "# Per-source instruction coverage\n\n"
                                + "| Source | Classes | Missed | Covered | Ratio | Status |\n"
                                + "| --- | --- | ---: | ---: | ---: | --- |\n");
        for (CoverageRow row : rows) {
            markdown.append("| `")
                    .append(row.path())
                    .append("` | ")
                    .append(row.classes().size())
                    .append(" | ")
                    .append(row.missed())
                    .append(" | ")
                    .append(row.covered())
                    .append(" | ")
                    .append(row.ratio() == null ? "n/a" : format(row.ratio()))
                    .append(" | ")
                    .append(row.status())
                    .append(" |\n");
        }
        write(markdownReport, markdown.toString());
    }

    private static List<Element> children(Element parent, String name) {
        List<Element> result = new ArrayList<>();
        for (Node node = parent.getFirstChild(); node != null; node = node.getNextSibling()) {
            if (node instanceof Element element && element.getTagName().equals(name)) {
                result.add(element);
            }
        }
        return result;
    }

    private static boolean isProductionSource(Path source) {
        String name = source.getFileName().toString();
        return name.endsWith(".java") || name.endsWith(".groovy") || name.endsWith(".gradle");
    }

    private static String sourceKey(String packageName, String sourceName) {
        return packageName.isBlank() ? sourceName : packageName + "/" + sourceName;
    }

    private static BigDecimal ratio(int covered, int total) {
        return BigDecimal.valueOf(covered).divide(BigDecimal.valueOf(total), 12, RoundingMode.DOWN);
    }

    private static String format(BigDecimal value) {
        return value.setScale(6, RoundingMode.DOWN).toPlainString();
    }

    private static String quote(String value) {
        return '"' + value.replace("\"", "\"\"") + '"';
    }

    private static String slash(Path path) {
        return path.toString().replace('\\', '/');
    }

    private static void write(Path target, String contents) throws IOException {
        Files.createDirectories(target.getParent());
        Files.writeString(target, contents, StandardCharsets.UTF_8);
    }

    private record SourceInventory(String relativePath, Path physicalPath) {}

    private record SourceCoverage(int missed, int covered) {
        private int total() {
            return missed + covered;
        }
    }

    private record CoverageDocument(
            Map<String, SourceCoverage> sources, Map<String, List<String>> classes) {}

    private record CoverageRow(
            String path,
            List<String> classes,
            int missed,
            int covered,
            BigDecimal ratio,
            String status) {}
}
